// Event codes emitted by the workflow/approval orchestrators and runtime.
// Labels describe what the server recorded; they never imply approval, risk, or a send.
const EVENT_TYPE_LABELS: Readonly<Record<string, string>> = {
  WORKFLOW_CREATED: "Tạo lượt xử lý",
  WORKFLOW_STARTED: "Bắt đầu quy trình",
  WORKFLOW_PAUSED: "Tạm dừng chờ Founder",
  WORKFLOW_RESUME_REQUESTED: "Yêu cầu tiếp tục quy trình",
  WORKFLOW_WAITING_FOR_INPUT: "Chờ bổ sung dữ liệu",
  WORKFLOW_WAITING_FOR_DOCUMENT_INPUT: "Chờ bổ sung tài liệu",
  WORKFLOW_COMPLETED: "Quy trình đã chạy xong",
  WORKFLOW_EXTENDED_TO_DECISION_INITIAL_ROUTE: "Thêm bước: xác định tuyến quyết định",
  WORKFLOW_EXTENDED_TO_FINAL_RISK_CHECK: "Thêm bước: kiểm tra rủi ro cuối",
  WORKFLOW_EXTENDED_TO_DECISION_CARD: "Thêm bước: lập Decision Card",
  WORKFLOW_EXTENDED_TO_BANKING_INTERNAL_DISCOVERY: "Thêm bước: khảo sát phương án ngân hàng",
  WORKFLOW_EXTENDED_TO_BANKING_PRECHECK_READINESS: "Thêm bước: kiểm tra dữ liệu cho precheck",
  WORKFLOW_EXTENDED_TO_BANKING_PRECHECK_SUBMISSION_PROPOSAL: "Thêm bước: chuẩn bị yêu cầu precheck",
  WORKFLOW_EXTENDED_TO_BANKING_PRECHECK_EXECUTION: "Thêm bước: chạy precheck mô phỏng",
  WORKFLOW_EXTENDED_TO_DECISION_POST_PRECHECK_REVIEW: "Thêm bước: rà soát sau precheck",
  WORKFLOW_EXTENDED_TO_DECISION_DOCUMENT_HANDOFF: "Thêm bước: bàn giao chuẩn bị hồ sơ",
  WORKFLOW_EXTENDED_TO_INTERNAL_DECISION_PACKAGE: "Thêm bước: tổng hợp hồ sơ quyết định nội bộ",
  NODE_STARTED: "Bắt đầu tác vụ",
  NODE_WAITING: "Tác vụ đang chờ",
  NODE_COMPLETED: "Tác vụ đã chạy xong",
  NODE_FAILED_SAFE: "Tác vụ dừng an toàn",
  RISK_DEPENDENCIES_READY: "Đủ đầu vào cho đánh giá rủi ro",
  FINAL_RISK_CHECK_COMPLETED: "Kiểm tra rủi ro cuối đã chạy xong",
  APPROVAL_CHECKPOINTS_REGISTERED: "Đăng ký điểm phê duyệt",
  APPROVAL_REQUESTED: "Tạo yêu cầu phê duyệt",
  APPROVAL_RESOLVED: "Yêu cầu phê duyệt đã được xử lý",
  APPROVAL_EXPIRED: "Yêu cầu phê duyệt hết hiệu lực",
  PROTECTED_ACTION_ALLOWED: "Hành động được bảo vệ được cho phép",
  PROTECTED_ACTION_BLOCKED: "Hành động được bảo vệ bị chặn",
  BANKING_INPUT_SUPPLEMENT_ACCEPTED: "Tiếp nhận số tiền Founder bổ sung",
  BANKING_PRECHECK_SUBMISSION_AUTHORIZED: "Founder cho phép chạy precheck",
  BANKING_PRECHECK_DECLINED_BY_FOUNDER: "Founder không cho phép chạy precheck",
  BANKING_PRECHECK_RESULTS_READY: "Có kết quả precheck mô phỏng",
  BANKING_PRECHECK_EVIDENCE_REFERENCE_ACCEPTED: "Tiếp nhận bằng chứng precheck bổ sung",
  DOCUMENT_EVIDENCE_REFERENCE_ACCEPTED: "Tiếp nhận tài liệu Founder bổ sung",
  DOCUMENT_RELEASE_PACKAGE_READY: "Gói hồ sơ nội bộ sẵn sàng",
  READY_FOR_INTERNAL_DECISION: "Sẵn sàng tổng hợp quyết định nội bộ",
  INTERNAL_DECISION_PACKAGE_READY: "Hồ sơ quyết định nội bộ sẵn sàng",
  DECISION_CARD_READY: "Decision Card đã sẵn sàng",
  DECISION_CARD_REPLAY_RECOVERED: "Khôi phục Decision Card đã lưu",
  DECISION_NOT_EVALUABLE: "Decision Card chưa đủ cơ sở để đề xuất",
  FINAL_DECISION_AUTHORIZED: "Founder phê duyệt quyết định cuối",
  FINAL_DECISION_REJECTED: "Founder từ chối quyết định cuối",
  POST_DECISION_UPDATE_COMPLETED: "Cập nhật sau quyết định đã chạy xong",
  NEGOTIATION_TERMS_SENT_CONFIRMED: "Founder xác nhận đã gửi điều kiện đàm phán",
  NEGOTIATION_OUTCOME_RECORDED: "Ghi nhận kết quả đàm phán",
  EXTERNAL_DOCUMENT_SUBMISSION_DECLINED: "Founder không cho phép gửi hồ sơ ra ngoài",
  READY_FOR_EXTERNAL_SUBMISSION: "Hồ sơ sẵn sàng để gửi · chưa gửi",
};

/** Vietnamese label for a known event code, or `null` so the caller can show the raw code. */
export function eventTypeLabel(eventType: string): string | null {
  return EVENT_TYPE_LABELS[eventType] ?? null;
}
