"""Workflow node identifiers owned by the application layer."""

from enum import StrEnum

from pydantic import BaseModel, ConfigDict

from opc_mis.domain.enums import WorkflowStatus


class WorkflowNode(StrEnum):
    """Nodes currently implemented by the Planner intake slice."""

    DATASET_INGESTION = "DATASET_INGESTION"
    PLANNER_INTAKE = "PLANNER_INTAKE"
    INITIAL_ASSESSMENT = "INITIAL_ASSESSMENT"
    FINANCE_ASSESSMENT = "FINANCE_ASSESSMENT"
    OPERATIONS_ASSESSMENT = "OPERATIONS_ASSESSMENT"
    INITIAL_RISK_SCAN = "INITIAL_RISK_SCAN"
    INITIAL_RISK_PRE_SCAN = "INITIAL_RISK_PRE_SCAN"
    INITIAL_RISK_FINALIZATION = "INITIAL_RISK_FINALIZATION"
    DECISION_ROUTE_PLANNING = "DECISION_ROUTE_PLANNING"
    DECISION_ROUTE_PLANNED = "DECISION_ROUTE_PLANNED"
    BANKING_DISCOVERY_HANDOFF = "BANKING_DISCOVERY_HANDOFF"
    BANKING_DISCOVERY_REQUESTED = "BANKING_DISCOVERY_REQUESTED"
    BANKING_INTERNAL_DISCOVERY = "BANKING_INTERNAL_DISCOVERY"
    BANKING_INTERNAL_OPTIONS_READY = "BANKING_INTERNAL_OPTIONS_READY"
    BANKING_PRECHECK_READINESS = "BANKING_PRECHECK_READINESS"
    DECISION_POST_BANKING_REVIEW = "DECISION_POST_BANKING_REVIEW"
    BANKING_INPUT_SUPPLEMENT = "BANKING_INPUT_SUPPLEMENT"
    BANKING_PRECHECK_READY = "BANKING_PRECHECK_READY"
    BANKING_PRECHECK_SUBMISSION_PROPOSAL = (
        "BANKING_PRECHECK_SUBMISSION_PROPOSAL"
    )
    BANKING_PRECHECK_SUBMISSION_AUTHORIZED = (
        "BANKING_PRECHECK_SUBMISSION_AUTHORIZED"
    )
    BANKING_PRECHECK_DECLINED = "BANKING_PRECHECK_DECLINED"
    BANKING_PRECHECK_EXECUTION = "BANKING_PRECHECK_EXECUTION"
    BANKING_PRECHECK_RESULTS_READY = "BANKING_PRECHECK_RESULTS_READY"
    DECISION_POST_PRECHECK_REVIEW = "DECISION_POST_PRECHECK_REVIEW"
    DECISION_POST_PRECHECK_REVIEW_COMPLETED = (
        "DECISION_POST_PRECHECK_REVIEW_COMPLETED"
    )
    DECISION_DOCUMENT_HANDOFF = "DECISION_DOCUMENT_HANDOFF"
    DOCUMENT_PREPARATION = "DOCUMENT_PREPARATION"
    DOCUMENT_INPUT_INTAKE = "DOCUMENT_INPUT_INTAKE"
    DOCUMENT_RELEASE_PACKAGE_READY = "DOCUMENT_RELEASE_PACKAGE_READY"
    READY_FOR_INTERNAL_DECISION = "READY_FOR_INTERNAL_DECISION"
    INTERNAL_DECISION_PACKAGE_ASSEMBLY = "INTERNAL_DECISION_PACKAGE_ASSEMBLY"
    INTERNAL_DECISION_PACKAGE_READY = "INTERNAL_DECISION_PACKAGE_READY"
    FINAL_RISK_CHECK = "FINAL_RISK_CHECK"
    FINAL_RISK_READY = "FINAL_RISK_READY"
    DECISION_CARD_COMPOSITION = "DECISION_CARD_COMPOSITION"
    DECISION_CARD_READY = "DECISION_CARD_READY"
    FINAL_DECISION_APPROVAL = "FINAL_DECISION_APPROVAL"
    FINAL_DECISION_REJECTED = "FINAL_DECISION_REJECTED"
    POST_DECISION_UPDATE = "POST_DECISION_UPDATE"
    NEGOTIATION_IN_PROGRESS = "NEGOTIATION_IN_PROGRESS"
    NEGOTIATION_TERMS_SENT = "NEGOTIATION_TERMS_SENT"
    NEGOTIATION_OUTCOME_RECEIVED = "NEGOTIATION_OUTCOME_RECEIVED"
    NEGOTIATION_FINAL_CONFIRMATION = "NEGOTIATION_FINAL_CONFIRMATION"
    FINAL_DECISION_ACCEPTED = "FINAL_DECISION_ACCEPTED"
    FINAL_DECISION_NOT_ACCEPTED = "FINAL_DECISION_NOT_ACCEPTED"
    EXTERNAL_DOCUMENT_SUBMISSION_PROPOSAL = (
        "EXTERNAL_DOCUMENT_SUBMISSION_PROPOSAL"
    )
    EXTERNAL_DOCUMENT_SUBMISSION_AUTHORIZED = (
        "EXTERNAL_DOCUMENT_SUBMISSION_AUTHORIZED"
    )
    EXTERNAL_DOCUMENT_SUBMISSION_DECLINED = (
        "EXTERNAL_DOCUMENT_SUBMISSION_DECLINED"
    )
    READY_FOR_EXTERNAL_SUBMISSION = "READY_FOR_EXTERNAL_SUBMISSION"
    # Retained for persisted-run/API compatibility. The current implemented
    # Document phase no longer enters any external-release node.
    DOCUMENT_EXTERNAL_RELEASE_PROPOSAL = "DOCUMENT_EXTERNAL_RELEASE_PROPOSAL"
    DOCUMENT_EXTERNAL_RELEASE_AUTHORIZED = "DOCUMENT_EXTERNAL_RELEASE_AUTHORIZED"
    DOCUMENT_EXTERNAL_RELEASE_DECLINED = "DOCUMENT_EXTERNAL_RELEASE_DECLINED"
    BANKING_PRECHECK_EVIDENCE_INTAKE = "BANKING_PRECHECK_EVIDENCE_INTAKE"
    BANKING_PRECHECK_RETRY_REQUIRED = "BANKING_PRECHECK_RETRY_REQUIRED"
    RISK_WAITING_FOR_FACTS = "RISK_WAITING_FOR_FACTS"
    RISK_FINALIZING = "RISK_FINALIZING"
    APPROVAL_GATE = "APPROVAL_GATE"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    PROTECTED_ACTION_AUTHORIZED = "PROTECTED_ACTION_AUTHORIZED"
    PROTECTED_ACTION_REJECTED = "PROTECTED_ACTION_REJECTED"
    INITIAL_ASSESSMENT_COMPLETED = "INITIAL_ASSESSMENT_COMPLETED"


class WorkflowRunState(BaseModel):
    """Persisted state selected by the Orchestrator after a node attempt."""

    model_config = ConfigDict(frozen=True)

    workflow_run_id: str
    dataset_id: str
    evaluation_case_id: str | None
    status: WorkflowStatus
    current_node: str
    blocked_node: str | None = None
    blocked_reason: str | None = None
    pending_request_ids: tuple[str, ...] = ()
